version: "3.8"

services:
   video-upload:
      build: .
      ports:
         - "8080:8080"
      environment:
         - URL_AUTH_SERVICE=${URL_AUTH_SERVICE}
         - URL_STATUS_TRACKER_SERVICE=${URL_STATUS_TRACKER_SERVICE}
         - AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
         - AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
         - AWS_S3_SESSION_TOKEN=${AWS_S3_SESSION_TOKEN}
         - AWS_S3_REGION=${AWS_S3_REGION}
         - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      env_file:
         - .env
